# Generated by Django 2.2 on 2020-12-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_patient_presscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_presscription',
            name='presscription',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
